#!/bin/zsh

# コピーしてきたいデータの場所
targetDir="${PWD}/"

# コピー下のデータの場所に移動する
cd `dirname $0`

# コピー元のデータの場所
baseDir="${PWD}/"

rsync -a $baseDir $targetDir --exclude '/node_modules/' --exclude '/.git/' --exclude 'data-cp'
